# Generated by Django 4.2.13 on 2024-05-24 14:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_post_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='photos/%Y/%m/%d'),
            preserve_default=False,
        ),
    ]
